name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # 手動で実行ボタンを押してデプロイすることも可能にする設定

# GitHub Pagesへのデプロイに必要な権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

# 二重ビルドを防ぐため、新しいプッシュがあったら古い実行中のジョブをキャンセルする
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build Astro Site
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4